-- Drop table if exists boardState_tiles cascade ;
-- drop table if exists players cascade ;
-- drop table if exists scenario_tiles cascade ;
-- drop table if exists scenarios cascade ;
-- drop table if exists sessions cascade ;

CREATE TABLE IF NOT EXISTS players
(
    player_id INTEGER
        GENERATED ALWAYS AS IDENTITY
        CONSTRAINT pk_player_id
                     PRIMARY KEY,
    username VARCHAR(10)
        DEFAULT 'guest'
        CONSTRAINT NN_username
                     NOT NULL
        CONSTRAINT uq_usename
                    UNIQUE,
    password  VARCHAR(20)
        CONSTRAINT NN_password
                    NOT NULL
        CONSTRAINT ck_password
                    CHECK ((length(password) >= 4))
)
;

CREATE TABLE IF NOT EXISTS scenarios (
    scenario_id INTEGER
        GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_scenario_id
                    PRIMARY KEY,
    boardSize numeric
        CONSTRAINT nn_boardSize
                    NOT NULL,
    starRule numeric
        CONSTRAINT nn_starRule
                    NOT NULL
)
;

CREATE TABLE IF NOT EXISTS scenario_tiles (
    scenario_id INTEGER
        CONSTRAINT fk_scenario_id REFERENCES scenarios (scenario_id),
    coordinateX numeric,
    coordinateY numeric,
    region numeric
        CONSTRAINT nn_region
            NOT NULL,
    CONSTRAINT pk_comp PRIMARY KEY (coordinateX, coordinateY, scenario_id)
)
;



CREATE TABLE IF NOT EXISTS sessions (
    session_id INTEGER
                GENERATED ALWAYS AS IDENTITY
        CONSTRAINT pk_session_id PRIMARY KEY,
    player_id INTEGER
        CONSTRAINT fk_player_id REFERENCES players (player_id),
    scenario_id INTEGER
        CONSTRAINT fk_scenario_id REFERENCES scenarios (scenario_id),
    time interval
        CONSTRAINT nn_time
                NOT NULL,
    isSolved boolean
        CONSTRAINT nn_isSolved
                NOT NULL
)
;

CREATE TABLE IF NOT EXISTS boardState_tiles (
    session_id INTEGER
        CONSTRAINT fk_session_id REFERENCES sessions (session_id) on delete cascade,
    coordinateX numeric,
    coordinateY numeric,
    hasStarPlaced boolean
        CONSTRAINT nn_hasStarPlaces
                NOT NULL,
    CONSTRAINT pk_composite PRIMARY KEY (coordinateX, coordinateY,session_id)
)
;